### PR TITLE
Set up Project Gradle Dependencies

### PR DESCRIPTION
**Pull request by mikailyusuf**
## This PR adds
Gradle Dependency Management With BuildSrc and Kotlin DSL
## Considerations and implementation
To achieve modularity and simplicity when the app grows.
### How to test
N/A for now rely on regression and unit testing, these changes can be tested more easily when Other App features ar added
### Test(s) added
n/a
### Screenshots
| Before | After |
| ------ | ----- |
| n/a | n/a |

### CODE REVIEW

**Review by enyason — CHANGES_REQUESTED** [review]
is there any particular reason why KotlinVersion and NavVersion have a different naming format to other variables?

**Comment by mikailyusuf** [comment]
I would change them immediately.
One more thing When I Build the project it raises some issue with the Google Json file, am guessing that's something you would handle.

**Comment by enyason** [comment]
> I would change them immediately.
> One more thing When I Build the project it raises some issue with the Google Json file, am guessing that's something you would handle.

Can u remove anything pointing to firebase? not needed at the moment

**Comment by mikailyusuf** [comment]
All dependency variable names have been changed to camelCase

**Pull request merged**
